@startuml
skinparam {
  backgroundColor DarkCyan

  InterfaceBackgroundColor #CCFF33
  ArrowColor DeepSkyBlue
  QueueBorderColor blue
  QueueBackgroundColor DeepSkyBlue
}

interface start

control "Split input process" as split_proc
control "Generate Root (10 workers)" as generate_root_worker
control "Grow Root (10 workers)" as grow_worker
control "Spread Root (10 workers)" as spread_worker
control "Mkdir Root (10 workers)" as mkdir_worker

queue "Root block" as split_q
queue "Root node" as root_q
queue "Growed Root node" as growing_q
note right of growing_q
Next process is
Spred or Mkdir.
end note

queue Error as err #CC6699
interface end

start -|> split_proc
split_proc --|> split_q
split_q -|> generate_root_worker
generate_root_worker --|> root_q
root_q -|> grow_worker
grow_worker --|> growing_q

growing_q -|> spread_worker
growing_q --|> mkdir_worker

split_proc ..> err
generate_root_worker ..> err
grow_worker ..> err
spread_worker ..> err
mkdir_worker ..> err

err -|> end
@enduml