@startuml
skinparam {
  backgroundColor DarkCyan

  InterfaceBackgroundColor HotPink
  ArrowColor DeepSkyBlue
  QueueBorderColor blue
  QueueBackgroundColor DeepSkyBlue
}

interface start
queue "Split input" as split
queue "Root node" as root
queue Grow as growing
queue Spread as spreading 
queue Mkdir as mkdiring
queue Error as err #whitesmoke
interface end

start -|> split
split -|> root
root -|> growing
growing --|> spreading: "  OR"
growing --|> mkdiring

split ..> err
root ..> err
growing ..> err
spreading ..> err
mkdiring ..> err

err -|> end
@enduml