// Package gtree provides tree-structured output.
package gtree

import (
	"io"
	"os"

	"github.com/pkg/errors"
)

var (
	// ErrNilNode is returned if the argument *gtree.Node of OutputProgrammably function is nill.
	ErrNilNode = errors.New("nil node")
	// ErrNotRoot is returned if the argument *gtree.Node of OutputProgrammably function is not root of the tree.
	ErrNotRoot = errors.New("not root node")
)

// OutputProgrammably outputs tree to w.
// This function requires node generated by NewRoot function.
func OutputProgrammably(w io.Writer, root *Node, optFns ...OptFn) error {
	if root == nil {
		return ErrNilNode
	}
	if !root.isRoot() {
		return ErrNotRoot
	}

	conf, err := newConfig(optFns...)
	if err != nil {
		return err
	}

	idxCounter.reset()

	tree := newTree(conf.encode, conf.formatLastNode, conf.formatIntermedialNode, conf.dryrun, conf.fileExtensions)
	tree.addRoot(root)
	if err := tree.grow(); err != nil {
		return err
	}
	return tree.expand(w)
}

// MkdirProgrammably makes directories.
// This function requires node generated by NewRoot function.
func MkdirProgrammably(root *Node, optFns ...OptFn) error {
	if root == nil {
		return ErrNilNode
	}
	if !root.isRoot() {
		return ErrNotRoot
	}

	conf, err := newConfig(optFns...)
	if err != nil {
		return err
	}

	idxCounter.reset()

	tree := newTree(conf.encode, conf.formatLastNode, conf.formatIntermedialNode, conf.dryrun, conf.fileExtensions)
	tree.addRoot(root)
	if err := tree.grow(); err != nil {
		return err
	}

	if conf.dryrun {
		// TODO: コードから呼び出すときにわざわざdry-run指定しないといけないかつ、標準出力に出力するのも変だと思う。
		//       理想は、dry-run指定なしと標準出力なしで、node.validateName()の結果を返す
		return tree.expand(os.Stdout)
	}

	return tree.mkdir()
}

var (
	idxCounter = newCounter()
)

// NewRoot creates a starting node for building tree.
func NewRoot(text string) *Node {
	return newNode(text, rootHierarchyNum, idxCounter.next())
}

// Add adds a node and returns an instance of it.
// If a node with the same text already exists in the same hierarchy of the tree, that node will be returned.
func (parent *Node) Add(text string) *Node {
	for _, child := range parent.Children {
		if text == child.Name {
			return child
		}
	}

	current := newNode(text, parent.hierarchy+1, idxCounter.next())
	current.setParent(parent)
	parent.addChild(current)
	return current
}
