@startuml

' https://plantuml.com/ja/class-diagram

package "定期的にツイートを保存する(1)" {
    class Program {
        - interval
        - twitterConsumerKey
        - twitterConsumerSecret
        + FetchTweets()
        + DumpTweets()
    }
}

package "保存されたリツイート/ツイートを確認する(2)" {
    class Visualizer {
        - tweets: []Tweet
        + ParseTweets()
        + DisplayTweets()
        + SaveSelectedTweets()
    }

    class Tweet {
        - id : int
        - text : string
        - isSelected : bool
        + Text()
        + SetIsSelected()
        + IsSelected()
    }
}
@enduml